---
- name: subscription-manager
  hosts: all
  become: true
  vars:
    subscription_username: "admin"
    subscription_password: "start98!"
  tasks:
    - name: register with subscription-manager
      redhat_subscription:  
        state: present
        username: "{{ subscription_username }}"
        password: "{{ subscription_password }}"
        auto_attach: true
