---
  - name: create vm from template
    hosts: localhost
    #connection: local
    #gather_facts: no
    become: false
    vars:
      datastore: DATASTORE03
     
    tasks: 
    - name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
      vmware_datastore_info:
       hostname: 10.2.250.110
       username: labtest1@vsphere.local
       password: Labtest@@2022
       datacenter_name: HPE-LAB-DC
       validate_certs: no
      delegate_to: localhost
      register: info

    - name: test
      ansible.builtin.debug:
       msg: " DataStoreName {{ item.name }} - DataStoreSize {{ item.freeSpace }} "
      loop: "{{ info.datastores }}"
      when: item.name != "DS-Ehab" 


#    - debug:
#       #var: cluster_facts["datastores"][1].name
#       var: info|default([])




