---
  - name: Enable / Disable Ports from firewall
    hosts: all

    tasks:
        - name: ICMP block echo-request
          firewalld:
            icmp_block: echo-request
            state: enabled
        - name: ICMP block echo-reply
          firewalld:
            icmp_block: echo-reply
            state: enabled

        - name: add firewalld port based rules
          firewalld:
             permanent: yes
             immediate: yes
             port: 25/tcp
             state: enabled
      
        - name: Get info on firewalld state
          command: "firewall-cmd --list-all"
          register: fw_out
        - debug:
                var: fw_out.stdout_lines
