- name: VMware Rest Test
  hosts: localhost
  become: false
  gather_facts: false

  collections:
  - vmware.vmware_rest

  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
    - name: Include Secret Environment Items
      include_vars:
        file: variables.yml
        name: vc


    - name: get vm moid
      vmware.vmware_rest.vcenter_vm_info:
#      vcenter_vm_info:
       vcenter_hostname: "{{ vc.vcenter_host }}"
       vcenter_password: "{{ vc.vcenter_password }}"
       vcenter_username: "{{ vc.vcenter_username }}"
       vcenter_validate_certs: "{{ vc.vcenter_validate_certs }}"
      register: vm_find_res

