---
- name: ssh config
  hosts: all
  gather_facts: no
  tasks:

- name: configure login.warns
  copy:
   src=/var/lib/awx/projects/files/login.warn
   dest=/etc/login.warn
  notify: restart ssh
- name: configure /etc/motd
  copy:
   src=/var/lib/awx/projects/files/motd
   dest=/etc/motd
  notify: restart ssh
- name: Disable SELinux
  selinux:
    state: disabled
- name: modifying ssh config file
    shell: echo "Banner /etc/login.warn" >> /etc/ssh/sshd_config
    notify: restart ssh
